Aim : Implement a program to handle Arithmetic exception, Array Index
Out of Bounds. The user enters two numbers Num1 and Num2. The division of
Num1 and Num2 is displayed. If Num1 and Num2 are not integers, the
program would throw a Number Format Exception. If Num2 were zero, the
program would throw an Arithmetic Exception. Display the exception.


import java.util.Scanner;
class exception
{
 void arthmaticException( ) 
 {
 //method to check arthmaticException
Scanner sc=new Scanner(System.in);                          //creating object of scanner class
 boolean valid;
 valid=false;
                                                            // intializing temp variable declaration
 while(!valid) 
 {
 try 
 {
  //try block
 
 System.out.println("Enter Two Numbers ::");
 int num1=sc.nextInt();//taking first num as input from user
 int num2=sc.nextInt();//taking second num as input from user
 double c=num1/num2;//dividing num1 by num2
 System.out.println("Division is "+c);//printing result
 valid=true;//changing value of temp variable
 }
 catch (Exception e) {
 //catch block after exception occur
 System.out.println("\t\tCannot Divide by Zero \n\t\tEnter Valid Denominator....\n");
 //printing sentence when denominator is 0
 }
 }
 }
 void ArrayOutOfBound(int [] arr) 
 {
                                                                         //method to check ArrayOutOfBound
Scanner sc=new Scanner(System.in);//creating object of
scanner class
boolean valid;
valid=false;                                                             // intializing temp variable declaration
 while(!valid) 
 {
 try 
 {
                                                                        //try block
 
System.out.print("\nEnter the Index No. of Element which you want to print ::");
 int i=sc.nextInt();//taking array index from user
 System.out.println( arr[i]+" is present at given index");
                                                                        //if index is there in array printing value at that index
 valid =true;//changing value of temp variable
 }
 catch(Exception e) {
 //catch block after exception occur
 System.out.println(" \t\tInvalid Index try again...\n");
 //printing invalid index when index out of bound
 }

 }
 }

}

//======================= CLASS Main =======================//


public class Main {
 public static void main(String[] args) {          //main method to start execution of program
 exception e=new exception();                      //creating object of
exception class
 Scanner sc=new Scanner(System.in);                //creating object of scanner class
 int n;
                                                   //when input is 1
 e.arthmaticException();                          //calling
arthmaticException method

 System.out.println("==========================================================");

 //when input is 2
 int[] arr= {1,4,5,2,3,8};
 e.ArrayOutOfBound(arr);//calling
ArrayOutOfBound method

 System.out.println("==========================================================");

}
}
/* 
